### ISSUE TITLE
 Option: use search queries from previous search

### ISSUE THREAD

**Issue by g-back** [stockbal/abap-code-search-ui#2]
Hi Ludwig,
first of all - thanks for the tool, it's a great help.

What would you think about an option to keep the input from the previous search?
A similar option exists for the standard ADT Object search (CTRL+SHIFT+A), the option is called "Use Pattern from Previous Search":

![image](https://user-images.githubusercontent.com/27279305/181226367-98c9f891-9a3e-4681-a1ec-e75b9c603bd7.png)

Specifically, I'm talking about the search pattern, object name and filters.

I'm not sure how difficult this would be to achieve and it's not super important, just a nice quality of life feature (If you have any pointers, I could even take a look myself ).

Thanks.

**Comment by stockbal** [comment]
Hi Goran,

I am glad the plugin is useful for you 🙂.

There is an option to open the executed query again from the search result view. 
![image](https://user-images.githubusercontent.com/35834861/181353215-242b7b4c-536f-4a3d-b928-41d6c129926d.png)
This will open the search dialog with all the parameters used to execute a given search. There is even a shortcut for this Ctrl+O.

Besides that, I have some plans to maybe include a dropdown in the search dialog, which would allow the user to choose from the last 10 (could be a configurable value) executed queries. This feature could perhaps also be combined with the setting you are proposing, to always load the most recent query immediately into the dialog.

Regards,
Ludwig

**Comment by g-back** [comment]
Thanks - did not see that function, that's exactly what I needed. Your plans also sound great, so I'll just close this!
