### ISSUE TITLE
Display matching string as tooltip in search result

### ISSUE THREAD

**Issue by robertstrasser** [stockbal/abap-code-search-ui#4]
Hi Ludwig,

thanks for your great work! I would like to suggest you an improvement in the search results.

When using the function `Get Where-used List`, the results are displayed with the possibility to display the entire matching statement in a tooltip:
![image](https://user-images.githubusercontent.com/37249782/196433115-eef5a93c-1aae-40d9-98e9-4ae4fd7f36ba.png)

When using a multiline regex search pattern, only the first line is displayed as result. Would it be possible to display the matching string as a tooltip as well?

**Example:**
* Search query:
![image](https://user-images.githubusercontent.com/37249782/196435144-4d8712fc-ae45-4305-881b-6c234b8f98ba.png)

* Search results:
![image](https://user-images.githubusercontent.com/37249782/196434468-2facc882-da20-4209-9677-8002e5747955.png)

* When jumping to the search result, the found string is highlighted.
![image](https://user-images.githubusercontent.com/37249782/196434796-8b093a5e-50f4-444f-8de0-28e17193acf5.png)

**Comment by stockbal** [comment]
Hello Robert,

this should be no problem. I think I even added a comment in the source code regarding this issue.
So, thanks for the reminder 😊.

Regards,
Ludwig

**Comment by stockbal** [comment]
Implemented in e13e36ed776f73b463352fd8370c67b1b15fe480
