### ISSUE TITLE
New Feature Idea: Enable posibility to export the search results in Excel Format

### ISSUE THREAD

**Issue by chiuarucatalin** [stockbal/abap-code-search-ui#5]
Hello Ludwig :)
I would like to enable the possibility to have an option in the ABAP Code Search (Search view) in Eclipse to export the findings/search results to an Excel file.

**Reasons:**
- in many cases is needed to perform usage analysis of certain used objects into a system, then export the results locally in an Excel file and then enhance the data with additional information which help in fullfiling the desired analysis. Such analysis can be a code review, performance analysis etc.

Possible Excel Format structure can be seen in the attached excel template.
[Idea Code Search Results export.xlsx](https://github.com/stockbal/abap-code-search-ui/files/10884984/Idea.Code.Search.Results.export.xlsx)

Thank you so much in considering this new feature which from my point of view will create a lot of added value.
Regards,
Cata

**Comment by stockbal** [comment]
Hi Catalin,

nice idea 😊.

What do you think about using CSV as a format instead? I could provide a similar dialog as it is used in the Data Preview Editor 
![image](https://user-images.githubusercontent.com/35834861/222893613-bc0eeb70-e6f2-49eb-b409-daf52a3eec58.png)
to get the user some customization options.

Excel format would also be possible, but it would require additional libraries that are not by default part of the Eclipse Installation.

Best Regards,
Ludwig

**Comment by chiuarucatalin** [comment]
Hi Ludwig,
.csv File is perfectly fine with me. Also great to have the options which
you highlighted below,
Thanks,
Cata

**Comment by stockbal** [comment]
Feature was added with v1.6.0 (7cc6de397fe1a0d25f3d7a4aa66c5c22767b4302)
New Version of the plug-in is available via the usual update sites or the eclipse marketplace
